project: default
destination:
  namespace: student-17
  name: in-cluster
syncPolicy:
  automated: {}
sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.4.0
    helm:
      valueFiles:
        - $values/jenkins/values.yaml
    chart: jenkins
  - repoURL: 'https://github.com/atkiis/argocd-katas-testing17'
    targetRevision: main
    ref: values